/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Animal;
import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class AnimalDetails_GUI extends javax.swing.JFrame {
        Animal searchedAnimal = main.Main.menuFuncs.getSearchedAnimal();
        String appointmentHistory = "";
        
    /**
     * Creates new form AnimalDetails_GUI
     */
    public AnimalDetails_GUI() {
        initComponents();
        
        name_lbl.setText("Nome: " + searchedAnimal.getName());
        age_lbl.setText("Idade: " + searchedAnimal.getAge());
        animalSpecies_lbl.setText("Especie: " + searchedAnimal.getAnimalSpecies());
        details_lbl.setText(searchedAnimal.getDetails());
        for (Integer key : searchedAnimal.getAppointments().keySet()) {
            appointmentHistory += (searchedAnimal.getAppointments().get(key).toString()) + "\n=-=-=-=-=-=-=-=-=\n";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        appointmentsHistory_btn = new javax.swing.JButton();
        details_lbl = new javax.swing.JLabel();
        detailsTitle_lbl = new javax.swing.JLabel();
        animalSpecies_lbl = new javax.swing.JLabel();
        age_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        goBack_btn = new javax.swing.JButton();
        aumigoBG_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        appointmentsHistory_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appointmentsHistory_btn.setText("Historico de Consultas");
        appointmentsHistory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsHistory_btnActionPerformed(evt);
            }
        });
        jPanel1.add(appointmentsHistory_btn);
        appointmentsHistory_btn.setBounds(30, 401, 250, 40);

        details_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        details_lbl.setForeground(new java.awt.Color(255, 255, 255));
        details_lbl.setText("Alergias etc...");
        jPanel1.add(details_lbl);
        details_lbl.setBounds(40, 310, 440, 40);

        detailsTitle_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        detailsTitle_lbl.setForeground(new java.awt.Color(255, 255, 255));
        detailsTitle_lbl.setText("Detalhes:");
        jPanel1.add(detailsTitle_lbl);
        detailsTitle_lbl.setBounds(40, 280, 120, 40);

        animalSpecies_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        animalSpecies_lbl.setForeground(new java.awt.Color(255, 255, 255));
        animalSpecies_lbl.setText("Especie:");
        jPanel1.add(animalSpecies_lbl);
        animalSpecies_lbl.setBounds(40, 220, 430, 40);

        age_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        age_lbl.setForeground(new java.awt.Color(255, 255, 255));
        age_lbl.setText("Idade:");
        jPanel1.add(age_lbl);
        age_lbl.setBounds(40, 160, 430, 40);

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        name_lbl.setText("Nome:");
        jPanel1.add(name_lbl);
        name_lbl.setBounds(40, 100, 430, 40);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(380, 440, 100, 30);

        goBack_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBack_btn.setText("VOLTAR");
        goBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btnActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn);
        goBack_btn.setBounds(380, 400, 100, 31);

        aumigoBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUMIGO_BG.png"))); // NOI18N
        jPanel1.add(aumigoBG_lbl);
        aumigoBG_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.MenuFuncs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void goBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new FindAnimal_GUI());
    }//GEN-LAST:event_goBack_btnActionPerformed

    private void appointmentsHistory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsHistory_btnActionPerformed
        JOptionPane.showMessageDialog(null, appointmentHistory);
    }//GEN-LAST:event_appointmentsHistory_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalDetails_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalDetails_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalDetails_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalDetails_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalDetails_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel age_lbl;
    public static javax.swing.JLabel animalSpecies_lbl;
    public static javax.swing.JButton appointmentsHistory_btn;
    private javax.swing.JLabel aumigoBG_lbl;
    public static javax.swing.JLabel detailsTitle_lbl;
    public static javax.swing.JLabel details_lbl;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton goBack_btn;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel name_lbl;
    // End of variables declaration//GEN-END:variables
}
