/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Owner;
import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class FindAnimal_GUI extends javax.swing.JFrame {
            private String selectedOwner;
            private String ownersCpf;
            private Owner owner;
            private String animalName;
            
    /**
     * Creates new form NewAppointment_GUI
     */
    public FindAnimal_GUI() {
        initComponents();
        whichAnimal_lbl.setVisible(false);
        newAppointment_btn.setVisible(false);
        animalDetails_btn.setVisible(false);
        animalsList_cbx.setVisible(false);
        
        ownersList_cbx.removeAllItems();
        String [] ownersNamesAndIdentifiers = main.Main.menuFuncs.getOwnersNamesAndIdentifier();
        for (String nameAndIdentifier : ownersNamesAndIdentifiers) {
            ownersList_cbx.addItem(nameAndIdentifier);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cantFindOwner_lbl = new javax.swing.JLabel();
        whichAnimal_lbl = new javax.swing.JLabel();
        whichOwner_lbl = new javax.swing.JLabel();
        animalDetails_btn = new javax.swing.JButton();
        newAppointment_btn = new javax.swing.JButton();
        animalsList_cbx = new javax.swing.JComboBox();
        ownersList_cbx = new javax.swing.JComboBox();
        exit_btn = new javax.swing.JButton();
        sendOwner_btn = new javax.swing.JButton();
        newOwner_btn = new javax.swing.JButton();
        goBack_btn = new javax.swing.JButton();
        aumigoBG_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        cantFindOwner_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantFindOwner_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cantFindOwner_lbl.setText("Nao encontra o dono na lista?");
        jPanel1.add(cantFindOwner_lbl);
        cantFindOwner_lbl.setBounds(20, 400, 380, 40);

        whichAnimal_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        whichAnimal_lbl.setForeground(new java.awt.Color(255, 255, 255));
        whichAnimal_lbl.setText("Qual animal desse dono?");
        jPanel1.add(whichAnimal_lbl);
        whichAnimal_lbl.setBounds(30, 180, 440, 40);

        whichOwner_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        whichOwner_lbl.setForeground(new java.awt.Color(255, 255, 255));
        whichOwner_lbl.setText("Qual o dono do animal?");
        jPanel1.add(whichOwner_lbl);
        whichOwner_lbl.setBounds(30, 90, 290, 40);

        animalDetails_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalDetails_btn.setText("Ficha do Animal");
        animalDetails_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalDetails_btnActionPerformed(evt);
            }
        });
        jPanel1.add(animalDetails_btn);
        animalDetails_btn.setBounds(270, 270, 150, 30);

        newAppointment_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newAppointment_btn.setText("Nova Consulta");
        newAppointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAppointment_btnActionPerformed(evt);
            }
        });
        jPanel1.add(newAppointment_btn);
        newAppointment_btn.setBounds(80, 270, 150, 30);

        animalsList_cbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalsList_cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item1", "Item2" }));
        animalsList_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalsList_cbxActionPerformed(evt);
            }
        });
        jPanel1.add(animalsList_cbx);
        animalsList_cbx.setBounds(30, 220, 440, 30);

        ownersList_cbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ownersList_cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));
        ownersList_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownersList_cbxActionPerformed(evt);
            }
        });
        jPanel1.add(ownersList_cbx);
        ownersList_cbx.setBounds(30, 130, 330, 30);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(380, 440, 100, 30);

        sendOwner_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sendOwner_btn.setText("ENVIAR");
        sendOwner_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOwner_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sendOwner_btn);
        sendOwner_btn.setBounds(370, 130, 100, 30);

        newOwner_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newOwner_btn.setText("Cadastrar Novo Cliente");
        newOwner_btn.setToolTipText("");
        newOwner_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOwner_btnActionPerformed(evt);
            }
        });
        jPanel1.add(newOwner_btn);
        newOwner_btn.setBounds(20, 440, 190, 25);

        goBack_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBack_btn.setText("VOLTAR");
        goBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btnActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn);
        goBack_btn.setBounds(380, 400, 100, 31);

        aumigoBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUMIGO_BG.png"))); // NOI18N
        jPanel1.add(aumigoBG_lbl);
        aumigoBG_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.MenuFuncs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void sendOwner_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOwner_btnActionPerformed
        selectedOwner = (String) ownersList_cbx.getSelectedItem();
        ownersCpf = main.Main.menuFuncs.extractIdentifier(selectedOwner);
        owner = main.Main.menuFuncs.getOwner(ownersCpf);
        String[] animalsNamesList = main.Main.menuFuncs.getOwner(ownersCpf).getAnimalsNames();
        animalsList_cbx.removeAllItems();
        
        for (String name : animalsNamesList) {
            animalsList_cbx.addItem(name);
        }
        
        whichAnimal_lbl.setVisible(true);
        newAppointment_btn.setVisible(true);
        animalDetails_btn.setVisible(true);
        animalsList_cbx.setVisible(true);
    }//GEN-LAST:event_sendOwner_btnActionPerformed

    private void newOwner_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOwner_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new NewOwner_GUI());
    }//GEN-LAST:event_newOwner_btnActionPerformed

    private void ownersList_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownersList_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownersList_cbxActionPerformed

    private void animalsList_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalsList_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalsList_cbxActionPerformed

    private void newAppointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAppointment_btnActionPerformed
        animalName = (String) animalsList_cbx.getSelectedItem();
        main.Main.menuFuncs.setSearchedAnimal(owner.getAnimal(animalName));
        Model.MenuFuncs_DAO.changeScreen(this, new NewAppointment_GUI());
    }//GEN-LAST:event_newAppointment_btnActionPerformed

    private void goBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new MainMenu_GUI());
    }//GEN-LAST:event_goBack_btnActionPerformed

    private void animalDetails_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalDetails_btnActionPerformed
        animalName = (String) animalsList_cbx.getSelectedItem();
        main.Main.menuFuncs.setSearchedAnimal(owner.getAnimal(animalName));
        Model.MenuFuncs_DAO.changeScreen(this, new AnimalDetails_GUI());
    }//GEN-LAST:event_animalDetails_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindAnimal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton animalDetails_btn;
    public static javax.swing.JComboBox animalsList_cbx;
    private javax.swing.JLabel aumigoBG_lbl;
    public static javax.swing.JLabel cantFindOwner_lbl;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton goBack_btn;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton newAppointment_btn;
    public static javax.swing.JButton newOwner_btn;
    public static javax.swing.JComboBox ownersList_cbx;
    public static javax.swing.JButton sendOwner_btn;
    public static javax.swing.JLabel whichAnimal_lbl;
    public static javax.swing.JLabel whichOwner_lbl;
    // End of variables declaration//GEN-END:variables
}
