/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class MainMenu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu_GUI
     */
    public MainMenu_GUI() {
        initComponents();
        welcome_lbl.setText("Seja bem vindo(a) " + main.Main.menuFuncs.getLoggedUser().getName().split(" ")[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome_lbl = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        newAnimal_btn = new javax.swing.JButton();
        animals_btn = new javax.swing.JButton();
        newOwner_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        aumigoBG_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        welcome_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome_lbl.setForeground(new java.awt.Color(255, 255, 255));
        welcome_lbl.setText("Seja bem-vindo(a)");
        jPanel1.add(welcome_lbl);
        welcome_lbl.setBounds(30, 80, 430, 40);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(370, 440, 110, 30);

        newAnimal_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newAnimal_btn.setText("Cadastrar Novo Animal");
        newAnimal_btn.setToolTipText("");
        newAnimal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAnimal_btnActionPerformed(evt);
            }
        });
        jPanel1.add(newAnimal_btn);
        newAnimal_btn.setBounds(60, 300, 380, 40);

        animals_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        animals_btn.setText("Animais");
        animals_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animals_btnActionPerformed(evt);
            }
        });
        jPanel1.add(animals_btn);
        animals_btn.setBounds(60, 140, 380, 40);

        newOwner_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newOwner_btn.setText("Cadastrar Novo Cliente");
        newOwner_btn.setToolTipText("");
        newOwner_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOwner_btnActionPerformed(evt);
            }
        });
        jPanel1.add(newOwner_btn);
        newOwner_btn.setBounds(60, 220, 380, 40);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOut_btn.setText("LOGOUT");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logOut_btn);
        logOut_btn.setBounds(370, 400, 110, 31);

        aumigoBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUMIGO_BG.png"))); // NOI18N
        jPanel1.add(aumigoBG_lbl);
        aumigoBG_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.MenuFuncs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void animals_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animals_btnActionPerformed
        if (main.Main.menuFuncs.hasRegisteredOwners()) {
            Model.MenuFuncs_DAO.changeScreen(this, new FindAnimal_GUI());
        } else {
            JOptionPane.showMessageDialog(null, "Impossivel acessar essa aba, nenhum cliente/animal cadastrado.");
        }
        
    }//GEN-LAST:event_animals_btnActionPerformed

    private void newOwner_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOwner_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new NewOwner_GUI());
    }//GEN-LAST:event_newOwner_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        if (main.Main.menuFuncs.logout()) {
            JOptionPane.showMessageDialog(null, "LogOut realizado com sucesso");
            Model.MenuFuncs_DAO.changeScreen(this, new SetUp_GUI());
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum usuario logado");
        }
        
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void newAnimal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAnimal_btnActionPerformed
        if (main.Main.menuFuncs.hasRegisteredOwners()) {
            Model.MenuFuncs_DAO.changeScreen(this, new NewAnimal_GUI());
        } else {
            JOptionPane.showMessageDialog(null, "Cadastre pelo menos um cliente antes de cadastrar um animal!");
        }
        
    }//GEN-LAST:event_newAnimal_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton animals_btn;
    private javax.swing.JLabel aumigoBG_lbl;
    public static javax.swing.JButton exit_btn;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton logOut_btn;
    public static javax.swing.JButton newAnimal_btn;
    public static javax.swing.JButton newOwner_btn;
    public static javax.swing.JLabel welcome_lbl;
    // End of variables declaration//GEN-END:variables
}
