/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Owner;
import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class NewAnimal_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewAnimal_GUI
     */
    public NewAnimal_GUI() {
        initComponents();
        ownersList_cbx.removeAllItems();
        String [] ownersNamesAndIdentifiers = main.Main.menuFuncs.getOwnersNamesAndIdentifier();
        for (String nameAndIdentifier : ownersNamesAndIdentifiers) {
            ownersList_cbx.addItem(nameAndIdentifier);
        }
        ownersList_cbx.setSelectedItem(ownersNamesAndIdentifiers[ownersNamesAndIdentifiers.length - 1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        animalSpecies_lbl = new javax.swing.JLabel();
        age_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        details_txt = new javax.swing.JTextField();
        animalSpecies_txt = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        goBack_btn = new javax.swing.JButton();
        send_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        ownersList_cbx = new javax.swing.JComboBox();
        details_lbl = new javax.swing.JLabel();
        whichOwner_lbl = new javax.swing.JLabel();
        newOwner_btn = new javax.swing.JButton();
        cantFindOwner_lbl = new javax.swing.JLabel();
        aumigoBG_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        animalSpecies_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        animalSpecies_lbl.setForeground(new java.awt.Color(255, 255, 255));
        animalSpecies_lbl.setText("Insira a especie do animal:");
        jPanel1.add(animalSpecies_lbl);
        animalSpecies_lbl.setBounds(50, 200, 360, 30);

        age_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        age_lbl.setForeground(new java.awt.Color(255, 255, 255));
        age_lbl.setText("Insira a idade do animal:");
        jPanel1.add(age_lbl);
        age_lbl.setBounds(50, 140, 330, 30);

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        name_lbl.setText("Insira o nome do animal:");
        jPanel1.add(name_lbl);
        name_lbl.setBounds(50, 80, 320, 30);

        details_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        details_txt.setText("Detalhes (alergias, doencas, etc...)");
        jPanel1.add(details_txt);
        details_txt.setBounds(50, 290, 330, 30);

        animalSpecies_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalSpecies_txt.setText("Especie");
        jPanel1.add(animalSpecies_txt);
        animalSpecies_txt.setBounds(50, 230, 330, 30);

        age_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        age_txt.setText("Idade");
        age_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txtActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt);
        age_txt.setBounds(50, 170, 330, 23);

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_txt.setText("Nome");
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt);
        name_txt.setBounds(50, 110, 330, 23);

        goBack_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBack_btn.setText("VOLTAR");
        goBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btnActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn);
        goBack_btn.setBounds(390, 410, 100, 30);

        send_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        send_btn.setText("ENVIAR");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        jPanel1.add(send_btn);
        send_btn.setBounds(170, 400, 120, 30);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(390, 450, 100, 30);

        ownersList_cbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ownersList_cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2" }));
        ownersList_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownersList_cbxActionPerformed(evt);
            }
        });
        jPanel1.add(ownersList_cbx);
        ownersList_cbx.setBounds(50, 360, 330, 30);

        details_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        details_lbl.setForeground(new java.awt.Color(255, 255, 255));
        details_lbl.setText("Escreva os detalhes sobre o animal:");
        jPanel1.add(details_lbl);
        details_lbl.setBounds(50, 260, 330, 40);

        whichOwner_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        whichOwner_lbl.setForeground(new java.awt.Color(255, 255, 255));
        whichOwner_lbl.setText("Qual o dono do animal?");
        jPanel1.add(whichOwner_lbl);
        whichOwner_lbl.setBounds(50, 320, 290, 40);

        newOwner_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newOwner_btn.setText("Cadastrar Novo Cliente");
        newOwner_btn.setToolTipText("");
        newOwner_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOwner_btnActionPerformed(evt);
            }
        });
        jPanel1.add(newOwner_btn);
        newOwner_btn.setBounds(20, 460, 200, 20);

        cantFindOwner_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantFindOwner_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cantFindOwner_lbl.setText("Nao encontra o dono na lista?");
        jPanel1.add(cantFindOwner_lbl);
        cantFindOwner_lbl.setBounds(20, 430, 360, 30);

        aumigoBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUMIGO_BG.png"))); // NOI18N
        jPanel1.add(aumigoBG_lbl);
        aumigoBG_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void age_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txtActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void goBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new MainMenu_GUI());
    }//GEN-LAST:event_goBack_btnActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        try {
            String selectedOwner = (String) ownersList_cbx.getSelectedItem();
            String ownersCpf = main.Main.menuFuncs.extractIdentifier(selectedOwner);
            Owner owner = main.Main.menuFuncs.getOwner(ownersCpf);        

            String name = name_txt.getText();
            int age = Integer.parseInt(age_txt.getText());
            String animalSpecies = animalSpecies_txt.getText();
            String details = details_txt.getText();

            owner.addNewAnimal(name, age, animalSpecies, details);
            JOptionPane.showMessageDialog(null, "Animal cadastrado com sucesso!");
            Model.MenuFuncs_DAO.changeScreen(this, new MainMenu_GUI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!\nCódigo do erro: " + e);
        }
    }//GEN-LAST:event_send_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.MenuFuncs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void ownersList_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownersList_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownersList_cbxActionPerformed

    private void newOwner_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOwner_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new NewOwner_GUI());
    }//GEN-LAST:event_newOwner_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAnimal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAnimal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel age_lbl;
    public static javax.swing.JTextField age_txt;
    public static javax.swing.JLabel animalSpecies_lbl;
    public static javax.swing.JTextField animalSpecies_txt;
    private javax.swing.JLabel aumigoBG_lbl;
    public static javax.swing.JLabel cantFindOwner_lbl;
    public static javax.swing.JLabel details_lbl;
    public static javax.swing.JTextField details_txt;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton goBack_btn;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel name_lbl;
    public static javax.swing.JTextField name_txt;
    public static javax.swing.JButton newOwner_btn;
    public static javax.swing.JComboBox ownersList_cbx;
    public static javax.swing.JButton send_btn;
    public static javax.swing.JLabel whichOwner_lbl;
    // End of variables declaration//GEN-END:variables
}
