/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class NewAppointment_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewAppointment_GUI
     */
    public NewAppointment_GUI() {
        initComponents();
        appointmentText_lbl.setText("Consulta do(a) " + main.Main.menuFuncs.getSearchedAnimal().getName().split(" ")[0]);
        vetsList_cbx.removeAllItems();
        String [] vetsNamesAndIdentifiers = main.Main.menuFuncs.getVetsNamesAndIdentifier();
        for (String nameAndIdentifier : vetsNamesAndIdentifiers) {
            vetsList_cbx.addItem(nameAndIdentifier);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        isTreated_lbl = new javax.swing.JLabel();
        appointmentReason_lbl = new javax.swing.JLabel();
        whichVet_lbl = new javax.swing.JLabel();
        appointmentDate_lbl = new javax.swing.JLabel();
        appointmentText_lbl = new javax.swing.JLabel();
        isTreated_cbx = new javax.swing.JComboBox();
        appointmentReason_txt = new javax.swing.JTextField();
        vetsList_cbx = new javax.swing.JComboBox();
        appointmentDate_txt = new javax.swing.JTextField();
        goBack_btn = new javax.swing.JButton();
        send_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        aumigoBG_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        isTreated_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        isTreated_lbl.setForeground(new java.awt.Color(255, 255, 255));
        isTreated_lbl.setText("O animal ja foi tratado?");
        jPanel1.add(isTreated_lbl);
        isTreated_lbl.setBounds(30, 240, 290, 30);

        appointmentReason_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appointmentReason_lbl.setForeground(new java.awt.Color(255, 255, 255));
        appointmentReason_lbl.setText("Qual o motivo da consulta?");
        jPanel1.add(appointmentReason_lbl);
        appointmentReason_lbl.setBounds(30, 170, 290, 30);

        whichVet_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        whichVet_lbl.setForeground(new java.awt.Color(255, 255, 255));
        whichVet_lbl.setText("Qual veterinario esta realizando o atendimento?");
        jPanel1.add(whichVet_lbl);
        whichVet_lbl.setBounds(30, 310, 450, 30);

        appointmentDate_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appointmentDate_lbl.setForeground(new java.awt.Color(255, 255, 255));
        appointmentDate_lbl.setText("Qual a data da consulta?");
        jPanel1.add(appointmentDate_lbl);
        appointmentDate_lbl.setBounds(30, 110, 330, 30);

        appointmentText_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        appointmentText_lbl.setForeground(new java.awt.Color(255, 255, 255));
        appointmentText_lbl.setText("Insira seu nome:");
        jPanel1.add(appointmentText_lbl);
        appointmentText_lbl.setBounds(30, 80, 440, 30);

        isTreated_cbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isTreated_cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Nao" }));
        jPanel1.add(isTreated_cbx);
        isTreated_cbx.setBounds(30, 270, 330, 30);

        appointmentReason_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        appointmentReason_txt.setText("Motivo da consulta");
        jPanel1.add(appointmentReason_txt);
        appointmentReason_txt.setBounds(30, 200, 330, 30);

        vetsList_cbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vetsList_cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item1", "Item2" }));
        jPanel1.add(vetsList_cbx);
        vetsList_cbx.setBounds(30, 340, 430, 30);

        appointmentDate_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        appointmentDate_txt.setText("Data");
        appointmentDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentDate_txtActionPerformed(evt);
            }
        });
        jPanel1.add(appointmentDate_txt);
        appointmentDate_txt.setBounds(30, 140, 330, 23);

        goBack_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBack_btn.setText("VOLTAR");
        goBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btnActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn);
        goBack_btn.setBounds(390, 410, 100, 30);

        send_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        send_btn.setText("ENVIAR");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        jPanel1.add(send_btn);
        send_btn.setBounds(140, 420, 150, 50);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(390, 450, 100, 30);

        aumigoBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUMIGO_BG.png"))); // NOI18N
        jPanel1.add(aumigoBG_lbl);
        aumigoBG_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void appointmentDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentDate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentDate_txtActionPerformed

    private void goBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new FindAnimal_GUI());
    }//GEN-LAST:event_goBack_btnActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        try {
            String appointmentDate = appointmentDate_txt.getText();
            String appointmentReason = appointmentReason_txt.getText();
            String isTreated = (String) isTreated_cbx.getSelectedItem();
            String selectedVet = (String) vetsList_cbx.getSelectedItem();
            String vetsUsername = main.Main.menuFuncs.extractIdentifier(selectedVet);    
            User vet = main.Main.menuFuncs.getVet(vetsUsername);

            if (main.Main.menuFuncs.addNewAppointment(main.Main.menuFuncs.getSearchedAnimal(), appointmentDate, appointmentReason, isTreated, vet)) {
                JOptionPane.showMessageDialog(null, "Consulta cadastrada com sucesso!");
                main.Main.menuFuncs.setSearchedAnimal(null);
                Model.MenuFuncs_DAO.changeScreen(this, new MainMenu_GUI());
            } else {
                JOptionPane.showMessageDialog(null, "Algo deu errado.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!\nCódigo do erro: " + e);
        }
    }//GEN-LAST:event_send_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.MenuFuncs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAppointment_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAppointment_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAppointment_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAppointment_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAppointment_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel appointmentDate_lbl;
    public static javax.swing.JTextField appointmentDate_txt;
    public static javax.swing.JLabel appointmentReason_lbl;
    public static javax.swing.JTextField appointmentReason_txt;
    public static javax.swing.JLabel appointmentText_lbl;
    private javax.swing.JLabel aumigoBG_lbl;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton goBack_btn;
    public static javax.swing.JComboBox isTreated_cbx;
    public static javax.swing.JLabel isTreated_lbl;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton send_btn;
    public static javax.swing.JComboBox vetsList_cbx;
    public static javax.swing.JLabel whichVet_lbl;
    // End of variables declaration//GEN-END:variables
}
