/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class NewOwner_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewClient_GUI
     */
    public NewOwner_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phoneNumber_lbl = new javax.swing.JLabel();
        cpf_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        phoneNumber_txt = new javax.swing.JTextField();
        cpf_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        goBack_btn = new javax.swing.JButton();
        send_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        aumigoBG_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        phoneNumber_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneNumber_lbl.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumber_lbl.setText("Insira o numero de telefone do cliente:");
        jPanel1.add(phoneNumber_lbl);
        phoneNumber_lbl.setBounds(50, 290, 360, 30);

        cpf_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpf_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cpf_lbl.setText("Insira o CPF do cliente:");
        jPanel1.add(cpf_lbl);
        cpf_lbl.setBounds(50, 190, 330, 30);

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        name_lbl.setText("Insira o nome do cliente:");
        jPanel1.add(name_lbl);
        name_lbl.setBounds(50, 100, 320, 30);

        phoneNumber_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumber_txt.setText("Numero de Telefone");
        jPanel1.add(phoneNumber_txt);
        phoneNumber_txt.setBounds(50, 320, 360, 30);

        cpf_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpf_txt.setText("CPF");
        cpf_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_txtActionPerformed(evt);
            }
        });
        jPanel1.add(cpf_txt);
        cpf_txt.setBounds(50, 220, 330, 23);

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_txt.setText("Nome");
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt);
        name_txt.setBounds(50, 130, 330, 23);

        goBack_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBack_btn.setText("VOLTAR");
        goBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btnActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn);
        goBack_btn.setBounds(390, 410, 100, 30);

        send_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        send_btn.setText("ENVIAR");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        jPanel1.add(send_btn);
        send_btn.setBounds(140, 420, 150, 50);

        exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(390, 450, 100, 30);

        aumigoBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AUMIGO_BG.png"))); // NOI18N
        jPanel1.add(aumigoBG_lbl);
        aumigoBG_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpf_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_txtActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void goBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btnActionPerformed
        Model.MenuFuncs_DAO.changeScreen(this, new MainMenu_GUI());
    }//GEN-LAST:event_goBack_btnActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        try {
            String name = name_txt.getText();
            String cpf = cpf_txt.getText();
            String phoneNumber = phoneNumber_txt.getText();

            if (main.Main.menuFuncs.addNewOwner(cpf, name, phoneNumber)) {
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
                Model.MenuFuncs_DAO.changeScreen(this, new NewAnimal_GUI());
            } else {
                JOptionPane.showMessageDialog(null, "CPF " + cpf_txt.getText() + " ja esta cadastrado.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!\nCódigo do erro: " + e);
        }
    }//GEN-LAST:event_send_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.MenuFuncs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOwner_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOwner_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOwner_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOwner_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOwner_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aumigoBG_lbl;
    public static javax.swing.JLabel cpf_lbl;
    public static javax.swing.JTextField cpf_txt;
    public static javax.swing.JButton exit_btn;
    public static javax.swing.JButton goBack_btn;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel name_lbl;
    public static javax.swing.JTextField name_txt;
    public static javax.swing.JLabel phoneNumber_lbl;
    public static javax.swing.JTextField phoneNumber_txt;
    public static javax.swing.JButton send_btn;
    // End of variables declaration//GEN-END:variables
}
